
trigger:
- master
steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'wget https://sig-repo.synopsys.com/artifactory/bds-integrations-release/com/synopsys/integration/synopsys-detect/6.9.1/synopsys-detect-6.9.1-air-gap.zip -P /tmp/'
- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: '/tmp/synopsys-detect-6.9.1-air-gap.zip'
    destinationFolder: '.'
    cleanDestinationFolder: true
    overwriteExistingFiles: false
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'ls /tmp'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'pwd'
